#!/usr/bin/env bash
set -euo pipefail

# Build temp auotincludes
incfile=include/autoincludes.inc
tmpfile=$(mktemp tmp_autoinc.XXXXXX)

find -L src/* \
    -name "*.inc" \
    -not -path "*/.idea/*" \
    -not -path "*/demo/*" \
| sort | while read -r file; do
    echo "#include \"../$file\"" >> "$tmpfile"
done

# Atomically commit the change:
if [[ ! -f "$incfile" ]] || ! diff -q "$tmpfile" "$incfile" >/dev/null; then
        echo "    Updated $incfile"
        mv "$tmpfile" "$incfile"
else
        rm -f "$tmpfile"
fi

