#!/usr/bin/env bash
set -euo pipefail
#cd "$(dirname "$0")"
# symlink subtrees
for i in $(cd ../subtrees; find -name .link_src); do 
   fullname=${i%/*}
   fullname=${fullname#*.} 
   dir=${fullname%/*}

   mkdir -p "src/linked/$dir"
   #calculate relative link offset:
   depth=$(echo "$fullname" | tr -cd '/' | wc -c)
   rel_path="../.."
   for ((j=0; j<depth; j++)); do rel_path="../$rel_path"; done
   #symlink it
   ln -sfn "${rel_path}/subtrees/${fullname}" \
              "src/linked/${fullname}"
done

# Build temp auotincludes
incfile=include/autoincludes.inc
tmpfile=$(mktemp tmp_autoinc.XXXXXX)

find -L src/* \
    -name "*.inc" \
    -not -path "*/.idea/*" \
    -not -path "*/demo/*" \
| sort | while read -r file; do
    echo "#include \"../$file\"" >> "$tmpfile"
done

# Atomically commit the change:
if [[ ! -f "$incfile" ]] || ! diff -q "$tmpfile" "$incfile" >/dev/null; then
        echo "    Updated $incfile"
        mv "$tmpfile" "$incfile"
else
        rm -f "$tmpfile"
fi

