// GeoModulesContextVariables.inc D.S. Leonard 2026
// Include files to add GeoModuleContext variable declarations and/or inline definitions
// These are shared variables for use between all GeoModules
// Alternatively add the variables directly here.
// Note, do not use .inc files as those are reserved for geomodules (for now).
// .inl or suc is fine.
// Add your conext varible files here
//use #ifdef GEOMODULES_CONTEXT_INCLUDES before includes, and #else before the rest  #endif
#include "../src/core/GeoModulesContextVariablesCore.inl"
#include "../src/core/GeoModulesContextVariablesColors.inl"
