#!/bin/bash
# run this script to build a preview of the preprocessed DetectorConstruction.hh
#  with all autoincludes pulled in.
mkdir Sim
touch Sim/CupDetectorConstruction.hh
g++ -I $(geant4-config --cflags) -H -dD -I ../ -P -E DetectorConstruction.hh -o pp
rm -rf Sim
less pp
rm pp
